global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'dagster'
    static_configs:
      - targets: ['dagster-metrics:9200']

  - job_name: 'mlflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'drift-monitor'
    static_configs:
      - targets: ['drift-monitor:9100']
